### ISSUE TITLE
Question: error using convert-di-to-inject

### ISSUE THREAD

**Issue by kscavenius** [ngxtension/ngxtension-platform#400] opened 2024-05-31 11:32 UTC
### Discussed in https://github.com/ngxtension/ngxtension-platform/discussions/399

<div type='discussions-op-text'>

<sup>Originally posted by **kscavenius** May 31, 2024</sup>
Hi

I am experimenting with the great convert-di-to-inject functionality. When running **ng g ngxtension:convert-di-to-inject** i get the error:
![image](https://github.com/ngxtension/ngxtension-platform/assets/18103936/a10503d8-6fa0-41ab-9a43-6bd42ab1d711)

My app compiles just fine, and it works great when specifying a component to migrate. 

All the best
Kristoffer</div>

**Comment by ilirbeqirii** [comment] 2024-06-06 11:37
Are you running the schematic on the root application path? And did you try it again with the newer versions? If yes, and the error persists, can you please give more details?

**Comment by eneajaho** [comment] 2024-06-06 13:25
Hello @kscavenius 
Can you provide some more information please. It's hard to find the root cause here. Also would be great if you could update to latest version and try again. This kind of error was solved once from what I remember.

**Comment by kscavenius** [comment] 2024-06-06 21:24
Hi
Thanks for getting back. I have some major issues with Webstorm (freezing constantly) and just switched to VS Code today. So I will have to focus on that. I will not be able to look into it until the end of next week due to a conference attendance.

But I guess my package.json answers it, right? I am on core 17.3.10, and 18 is required. My apologies.

Here is my package.json
```
{
  "name": "osint-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --base-href .",
    "watch": "ng build --watch --configuration development",
    "test": "jest",
    "find-dead-code": "ts-prune"
  },
  "jest": {
    "preset": "jest-preset-angular",
    "setupFilesAfterEnv": [
      "<rootDir>/setup-jest.ts"
    ]
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^17.3.10",
    "@angular/cdk": "^17.0.4",
    "@angular/common": "^17.3.10",
    "@angular/compiler": "^17.3.10",
    "@angular/core": "^17.3.10",
    "@angular/forms": "^17.3.10",
    "@angular/localize": "^17.3.10",
    "@angular/platform-browser": "^17.3.10",
    "@angular/platform-browser-dynamic": "^17.3.10",
    "@angular/router": "^17.3.10",
    "@total-typescript/ts-reset": "^0.5.1",
    "@videogular/ngx-videogular": "^8.0.0",
    "angular-highcharts": "^16.0.0",
    "bootstrap": "^5.3.2",
    "flag-icons": "^7.1.0",
    "highcharts": "^11.2.0",
    "highcharts-angular": "^4.0.0",
    "idb": "^8.0.0",
    "jspdf": "^2.5.1",
    "leaflet": "^1.9.4",
    "lodash": "^4.17.21",
    "ng2-google-charts": "^7.0.0",
    "ngx-clipboard": "^16.0.0",
    "ngxtension": "^3.4.0",
    "ol": "^8.2.0",
    "popper.js": "^1.16.1",
    "primeicons": "^6.0.1",
    "primeng": "^17.2.0",
    "proj4": "^2.9.2",
    "quill": "2.0.0-rc.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.4.1",
    "tui-image-editor": "^3.15.3",
    "zone.js": "~0.14.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^17.3.8",
    "@angular/cli": "^17.3.8",
    "@angular/compiler-cli": "^17.3.10",
    "@testing-library/angular": "^13.4.0",
    "@types/jasmine": "~5.1.0",
    "@types/jest": "^29.5.11",
    "@types/node": "^20.10.5",
    "jasmine-core": "~5.1.0",
    "jest": "^29.7.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "ts-prune": "^0.10.3",
    "typescript": "~5.2.2"
  }
}
```

Best regards
Kristoffer

**Comment by eneajaho** [comment] 2024-07-31 16:13
Hello @kscavenius 
In this release https://github.com/angular/angular/releases/tag/18.2.0-next.2 Angular added official support for inject migration. I'd recommend to try to run that migration too in your project and if there are issues, please open them in the Angular repo.

I will be closing the issues regarding migrations in ngxtension which are now directly supported in the fwk.

**Closed by eneajaho** 2024-07-31 16:13 UTC
Labels: bug
